### ISSUE TITLE
Modifying in memory files.

### ISSUE THREAD

**Issue by dazinator** [Permutatrix/rollup-plugin-hypothetical#10]
I am experimenting with rollupjs and hypothetical, via it's javascript API in a mocha test.

I initialise the plugin and provide some in memory files:

```
            var hypotheticalPlugin = hypothetical({
                files: files
            });
            hypotheticalPlugin.cwd = false;
            inputOptions.plugins = [hypotheticalPlugin];
```

I am then calling rollup multiple times, and it works as expected.

However if I modify an in memory file in my files array:

```
files[filePathB] = fs.readFileSync('testFiles/ModuleB/classbchanged.js', "utf-8");

```

And then call rollup again, using the same plugin instance - the modified file contents are not detected.
I think the plugin instance may have its own cache or copy of the files array, so despite me making a modification to a file, the plugin instance is perhaps oblivious.

If I do the following after changing the file and re-invoking rollup it works:

```
                     // Change file in files array, and then re-initialise hypothetical plugin so it will pick up the changes.
                      files[filePathB] = fs.readFileSync('testFiles/ModuleB/classbchanged.js', "utf-8");
                      hypotheticalPlugin = hypothetical({
                         files: files
                     });
                     inputOptions.plugins = [hypotheticalPlugin];

```
So it seems I have to re-initialise the plugin instance for the next rollup build before it will pick up the change.

I wondered if there is a way I can update file contents for an existing instance of the plugin?

**Comment by lemmabit** [comment]
Sorry for the long hiatus. This plugin does only read its input once, which is deliberate, since mutation of internal fields can often lead to "spooky action at a distance" bugs. It also applies certain transformations to its internal copy ahead of time for the sake of efficiency. If this still affects you, may I ask why you'd rather avoid recreating the plugin each time files are changed?

**Comment by lemmabit** [comment]
I'll close this as wontfix for now, but if it still matters to you, feel free to reopen and explain your use case.
