### ISSUE TITLE
Multiple Entry Points are not supported

### ISSUE THREAD

**Issue by storm1ng** [Permutatrix/rollup-plugin-hypothetical#12]
When we use [multiple entry points](https://rollupjs.org/guide/en#input) as described in the docs then this plugin will throw the following error:
>[!] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

**Comment by lemmabit** [comment]
I can't reproduce this, and I've added a test that the plugin works with multiple entry points. It may have been fixed by a change in Rollup's behavior. I'm closing this issue because of its age, but feel free to reopen it.
