### ISSUE TITLE
Keep reporting .json file not found in the system

### ISSUE THREAD

**Issue by joelchu** [Permutatrix/rollup-plugin-hypothetical#3]
It keeps reporting `.json` file(s) is not found (where the console show the correct path, and just `cat _path_showed` return the correct content.

Here my gulp setup 

```javascript
     gulp.task('dev:rollup' , (cb) =>
{
    pump([
        gulp.src(join(yeoman.script , '**' , '*.{tag,js,json}')),
        // sourcemaps.init(),
        grollup({
            entry: join('app' , 'scripts' , 'bundle.js'),
            format: 'iife',
            // cache: cache,
            plugins: [
                 riot(),
                 nodeResolve({
                     jsnext: true,
			         main: true,
			         browser: true
                 }),
                 json(),
                 commonJs(),
                 babel()
            ],
            globals: {
             	  riot: 'riot',
             	jquery: '$',
         		 Bacon: 'Bacon',
         	 immutable: 'Immutable',
                 fetch: 'fetch',
                lodash: '_'
           	},
         	external: [
         		'riot',
         		'jquery',
         		'Bacon',
         		'immutable',
                 'fetch',
                 'lodash'
         	]
        }),
        // sourcemaps.write(),
        gulp.dest(join(yeoman.dev , 'scripts'))
    ] , cb);
}); 
```

**Comment by Permutatrix** [comment]
I don't believe this is enough information. What do the failing `import` statements look like? What's your directory structure?

**Comment by Permutatrix** [comment]
It would be ideal if I could see your repository.

**Comment by Permutatrix** [comment]
Really, though, you shouldn't be using gulp-rollup for this. [rollup-stream](https://github.com/Permutatrix/rollup-stream) is what you should use, partly because it's far less susceptible to problems like this one.

**Comment by joelchu** [comment]
I will add all the code later on. The problem is whether I use this or not. If I remove the rollup-plugin-hypothetical the whole things stop working. The reason I think this plugin is the issue is because the error message is originated from this plugin.

**Comment by Permutatrix** [comment]
@joelchu rollup-plugin-hypothetical is only one part of gulp-rollup. You'll want to replace it entirely. Your setup would end up looking like something close to this:

```js
// import everything you were importing before (except for gulp-rollup).
// add these:
var rollupStream = require('rollup-stream');
var source = require('vinyl-source-stream');
// don't forget to declare the `cache` variable if you use the cache.
// var cache;

     gulp.task('dev:rollup' , (cb) =>
{
    pump([
        rollupStream({
            entry: join('app' , 'scripts' , 'bundle.js'),
            format: 'iife',
            // cache: cache,
            plugins: [
                 riot(),
                 nodeResolve({
                     jsnext: true,
                     main: true,
                     browser: true
                 }),
                 json(),
                 commonJs(),
                 babel()
            ],
            globals: {
                  riot: 'riot',
                jquery: '$',
                 Bacon: 'Bacon',
             immutable: 'Immutable',
                 fetch: 'fetch',
                lodash: '_'
            },
            external: [
                'riot',
                'jquery',
                'Bacon',
                'immutable',
                 'fetch',
                 'lodash'
            ]
            // , sourceMap: true
        })
        // .on('bundle', function(bundle) {
        //   cache = bundle;
        // })
        , source('bundle.js'),
        gulp.dest(join(yeoman.dev , 'scripts'))
    ] , cb);
});
```

I included sections for sourcemaps and caching, which you can uncomment if you want to use them. The commas are a bit weird because JavaScript has a pretty bad comma policy.

**Comment by joelchu** [comment]
Thanks, I will give it a try and report back here. Cheers.

**Comment by joelchu** [comment]
It works. Thanks. The cache also works. 

Sourcemap report: 

**Sourcemap is likely to be incorrect: a plugin was used to transform files, but didn't generate a sourcemap for the transformation. Consult https://github.com/rollup/rollup/wiki/Troubleshooting and the plugin documentation for more information**

Which I think its something to do with babel , still need to investigate further. Thanks for the help.

**Comment by Permutatrix** [comment]
@joelchu Awesome. Hopefully what you were experiencing wasn't a legitimate bug in gulp-rollup or rollup-plugin-hypothetical. If you do push the old code, I'll appreciate it if you point me to it so I can check.

**Comment by joelchu** [comment]
will do thanks for the help.
