### ISSUE TITLE
Usage in the Browser?

### ISSUE THREAD

**Issue by curran** [Permutatrix/rollup-plugin-hypothetical#8]
Greetings,

I'd like to use this plugin in a browser environment.

The only roadblock is the import `var path = require('path').posix;`, which is ending up as `undefined` in the browser build.

I wonder, would there be a simple way to avoid this import, so that the build can work in a browser environment?

One option appears to be https://github.com/suarasaur/node-path-posix

**Comment by lemmabit** [comment]
See my comment on PR #9:

> Hmm, I'm not sure I want to pull in a very old duplication of a Node API in order to paper over a deficiency in some other duplication. I don't see any reason for whatever is supplying the `path` package in your browser build to omit the `posix` export.
>
> If you're using rollup-plugin-node-builtins, there's an issue for this: https://github.com/calvinmetcalf/rollup-plugin-node-builtins/issues/33
>
> Browserify, on the other hand, seems to include a correct `posix` export. Perhaps you could use a Rollup plugin to alias the `path` import to `path-browserify`.
>
> I'm going to close this.

What's here already works in Node, should work in Browserify, and in Rollup with some tinkering. That's all I'm aiming for when it comes to compatibility, so I'm going to close this issue.

Feel free to reopen if you think any of those goals are unmet or if you have a reason for me to set a higher standard.

**Comment by curran** [comment]
Thanks for looking into this!

I will look into this more as well. In particular

>whatever is supplying the path package in your browser build

I don't know how this would be supplied, as it's a [Node API](https://nodejs.org/api/path.html) rather than an NPM package, so I can research more on how it might be supplied for a browser build.

Fingers crossed it can work

>in Rollup with some tinkering.

Will tinker and report back here if I do find a way to make it work.

Thanks for your work on this package!
